strictPeerDependencies: false
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
shellEmulator: true

ignoredBuiltDependencies:
  - sharp
onlyBuiltDependencies:
  - esbuild
  - lefthook
  - unrs-resolver
